version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/Simple-diet
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
   - location: scripts/remove_server.sh
     timeout: 300
     runas: root
  Install:
   - location: scripts/install_app.sh
     runas: root
  ApplicationStart:
   - location: scripts/start_server.sh
     runas: root
     timeout: 300