version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/Simple_diet
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
   - location: scripts/remove_server
     timeout: 300
     runas: root
  Install:
   - location: scripts/install_app
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     runas: root