# Generated by Django 4.1.4 on 2023-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_data',
            old_name='fucus',
            new_name='nutrient_fucus',
        ),
        migrations.AddField(
            model_name='food_data',
            name='meals_fucus',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
