# Generated by Django 4.1.4 on 2023-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_categories',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
