# Generated by Django 4.1.4 on 2023-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_rename_fucus_food_data_nutrient_fucus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='meals_fucus',
            field=models.IntegerField(choices=[(0, '아침'), (1, '점심'), (2, '저녁')], default=0),
        ),
    ]
