# Generated by Django 4.1.4 on 2023-02-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_data_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_data',
            name='category',
        ),
    ]
