# Generated by Django 4.1.4 on 2023-01-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_data_meals_fucus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='carbohydrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food_data',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food_data',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
