# Generated by Django 4.1.4 on 2023-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_data_carbohydrate_alter_food_data_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='nutrient_fucus',
            field=models.CharField(choices=[('P', '단백질'), ('F', '지방'), ('C', '탄수화물')], default='P', max_length=10),
        ),
    ]
