# Generated by Django 4.1.4 on 2023-01-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_data_nutrient_fucus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='meals_fucus',
            field=models.JSONField(),
        ),
    ]
