# Generated by Django 4.1.4 on 2023-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_food_data_meals_fucus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='meals_fucus',
            field=models.CharField(max_length=10),
        ),
    ]
