# Generated by Django 4.1.4 on 2023-02-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_alter_food_data_meals_fucus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
