# Generated by Django 4.1.6 on 2023-03-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Food_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein_type_first', models.CharField(max_length=30)),
                ('protein_type_second', models.CharField(max_length=30, null=True)),
                ('fat_type_first', models.CharField(max_length=30)),
                ('fat_type_second', models.CharField(max_length=30, null=True)),
                ('carbohydrate_type_first', models.CharField(max_length=30)),
                ('carbohydrate_type_second', models.CharField(max_length=30, null=True)),
                ('etc_type_first', models.CharField(max_length=30)),
                ('etc_type_second', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diet_nutrient_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protein_buffer', models.FloatField(default=0)),
                ('fat_buffer', models.FloatField(default=0)),
                ('carbohydrate_buffer', models.FloatField(default=0)),
                ('custom_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.meal_food_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
