# Generated by Django 4.1.6 on 2023-03-16 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_alter_diet_nutrient_manager_custom_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet_nutrient_manager',
            name='custom_manager',
        ),
        migrations.DeleteModel(
            name='Meal_Food_Type',
        ),
    ]
