# Generated by Django 4.1.4 on 2023-03-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protien', models.IntegerField(null=True)),
                ('fat', models.IntegerField(null=True)),
                ('carbohydrate', models.IntegerField(null=True)),
                ('foods', models.ManyToManyField(null=True, to='foods.food')),
            ],
        ),
        migrations.CreateModel(
            name='Meals_Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_option', models.IntegerField(null=True)),
                ('fat_option', models.IntegerField(null=True)),
                ('carbohydrate_option', models.IntegerField(null=True)),
                ('diet_status', models.FloatField()),
                ('many_meals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.meal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_custom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.meals_custom'),
        ),
    ]
