# Generated by Django 4.1.4 on 2023-02-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_buffer', models.FloatField()),
                ('fat_buffer', models.FloatField()),
                ('carbohydrate_buffer', models.FloatField()),
                ('food_number', models.IntegerField()),
            ],
        ),
    ]
