
BODY_INFO_DATA = {
    0 : {"age": 25,"weight": 110,"height": 173,"gender": "M","general_activities": 1.2,
        "excise_activity": 0.2,"diet_status": 1,"many_meals": 2},
    1 :{"age": 23, "weight": 67, "height": 145, "gender": "W", "general_activities": 1.4,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 3},
    2 : {"age": 30, "weight": 115, "height": 170, "gender": "M", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 2},
    3 :{"age": 22, "weight": 80, "height": 160, "gender": "W", "general_activities": 1.2,
        "excise_activity": 0.3, "diet_status": 0.8, "many_meals": 3},
    4 : {"age": 28, "weight": 125, "height": 190, "gender": "M", "general_activities": 1.4,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 2},
    5 : {"age": 25, "weight": 65, "height": 145, "gender": "W", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 3},
    6 : {"age": 33, "weight": 95, "height": 175, "gender": "M", "general_activities": 1.2,
        "excise_activity": 0.3, "diet_status": 1, "many_meals": 2},
    7 : {"age": 31, "weight": 85, "height": 150, "gender": "W", "general_activities": 1.4,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 3},
    8 : {"age": 24, "weight": 70, "height": 140, "gender": "M", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 2},
    9 : {"age": 20, "weight": 80, "height": 160, "gender": "W", "general_activities": 1.2,
        "excise_activity": 0.3, "diet_status": 1, "many_meals": 3},
    10 : {"age": 27, "weight": 100, "height": 180, "gender": "M", "general_activities": 1.4,
        "excise_activity": 0.2, "diet_status": 0.8, "many_meals": 2},
    11 : {"age": 35, "weight": 115, "height": 185, "gender": "W", "general_activities": 1.6,
       "excise_activity": 0.1, "diet_status": 1, "many_meals": 3},
    12 : {"age": 22, "weight": 75, "height": 155, "gender": "M", "general_activities": 1.2,
        "excise_activity": 0.3, "diet_status": 0.8, "many_meals": 2},
    13 : {"age": 32, "weight": 70, "height": 145, "gender": "W", "general_activities": 1.2,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 3},
    14 : {"age": 28, "weight": 80, "height": 155, "gender": "M", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 2},
    15 : {"age": 26, "weight": 60, "height": 172, "gender": "W", "general_activities": 1.4,
        "excise_activity": 0.3, "diet_status": 0.8, "many_meals": 3},
    16 : {"age": 34, "weight": 90, "height": 175, "gender": "M", "general_activities": 1.2,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 2},
    17 : {"age": 21, "weight": 55, "height": 145, "gender": "W", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 3},
    18 : {"age": 29, "weight": 105, "height": 185, "gender": "M", "general_activities": 1.4,
        "excise_activity": 0.3, "diet_status": 1, "many_meals": 2},
    19 : {"age": 36, "weight": 75, "height": 150, "gender": "W", "general_activities": 1.2,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 3},
    20 : {"age": 25, "weight": 85, "height": 165, "gender": "M", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 0.8, "many_meals": 2},
    21 : {"age": 33, "weight": 120, "height": 195, "gender": "W", "general_activities": 1.4,
        "excise_activity": 0.3, "diet_status": 1, "many_meals": 3},
    22 : {"age": 30, "weight": 70, "height": 140, "gender": "M", "general_activities": 1.2,
        "excise_activity": 0.2, "diet_status": 0.8, "many_meals": 2},
    23 : {"age": 24, "weight": 65, "height": 175, "gender": "W", "general_activities": 1.6,
        "excise_activity": 0.1, "diet_status": 1, "many_meals": 3},
    24 : {"age": 31, "weight": 95, "height": 170, "gender": "M", "general_activities": 1.4,
        "excise_activity": 0.3, "diet_status": 0.8, "many_meals": 2},
    25 : {"age": 27, "weight": 110, "height": 190, "gender": "W", "general_activities": 1.2,
        "excise_activity": 0.2, "diet_status": 1, "many_meals": 3}
}
