# Generated by Django 4.1.4 on 2023-03-01 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(max_length=2)),
                ('general_activities', models.FloatField()),
                ('excise_activity', models.FloatField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_kcalorie', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('total_carbohydrate', models.FloatField()),
                ('body_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metabolic_calculator.body_info')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
